'use server';
/**
 * @fileOverview Translates technical security risks into business-friendly language.
 *
 * This file defines a Genkit flow that takes a technical risk description as input and uses AI to
 * translate it into language that is easily understandable by non-technical stakeholders. This is used
 * to enhance the clarity and impact of PDF reports generated by the Sentinel Stack platform.
 *
 * @example
 * // Example usage:
 * const businessFriendlyRisk = await translateTechnicalRiskToBusinessLanguage(
 *   "The application is vulnerable to cross-site scripting (XSS)."
 * );
 *
 * // Expected output:
 * // "This vulnerability could allow attackers to inject malicious scripts into the application, potentially leading to data theft or unauthorized access to user accounts."
 *
 * @param {string} technicalRisk - The technical risk description to be translated.
 * @returns {string} A business-friendly translation of the technical risk.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

// Define the input schema for the technical risk translator flow
const TranslateTechnicalRiskInputSchema = z.string().describe('The technical risk description to be translated into business-friendly language.');
export type TranslateTechnicalRiskInput = z.infer<typeof TranslateTechnicalRiskInputSchema>;

// Define the output schema for the business-friendly risk translation
const TranslateTechnicalRiskOutputSchema = z.string().describe('A business-friendly translation of the technical risk.');
export type TranslateTechnicalRiskOutput = z.infer<typeof TranslateTechnicalRiskOutputSchema>;

// Define the prompt for translating technical risk to business language
const translateTechnicalRiskPrompt = ai.definePrompt({
  name: 'translateTechnicalRiskPrompt',
  input: { schema: TranslateTechnicalRiskInputSchema },
  output: { schema: TranslateTechnicalRiskOutputSchema },
  prompt: `Translate the following technical security risk into language that is easily understandable by non-technical stakeholders. Focus on the potential impact to the business, such as data theft, financial loss, or reputational damage.\n\nTechnical Risk: {{{$input}}}`,
});

// Define the Genkit flow for translating technical risk to business language
const translateTechnicalRiskFlow = ai.defineFlow(
  {
    name: 'translateTechnicalRiskFlow',
    inputSchema: TranslateTechnicalRiskInputSchema,
    outputSchema: TranslateTechnicalRiskOutputSchema,
  },
  async (technicalRisk) => {
    const { output } = await translateTechnicalRiskPrompt(technicalRisk);
    return output!;
  }
);

/**
 * Translates a technical security risk description into business-friendly language.
 *
 * @param {string} technicalRisk The technical risk description.
 * @returns {Promise<string>} A promise that resolves with the business-friendly translation.
 */
export async function translateTechnicalRiskToBusinessLanguage(technicalRisk: TranslateTechnicalRiskInput): Promise<TranslateTechnicalRiskOutput> {
  return translateTechnicalRiskFlow(technicalRisk);
}
