'use client';

import { useState } from 'react';
import { Bot, Loader2 } from 'lucide-react';

import { Button } from '@/components/ui/button';
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from '@/components/ui/dialog';
import { getAiSummaryAction } from '@/app/actions';
import { useToast } from '@/hooks/use-toast';
import { Alert, AlertDescription, AlertTitle } from '../ui/alert';

type AISummaryButtonProps = {
  findings: string;
};

export function AISummaryButton({ findings }: AISummaryButtonProps) {
  const [isOpen, setIsOpen] = useState(false);
  const [isLoading, setIsLoading] = useState(false);
  const [summary, setSummary] = useState('');
  const [error, setError] = useState('');
  const { toast } = useToast();

  const handleGenerateSummary = async () => {
    setIsLoading(true);
    setError('');
    setSummary('');

    const result = await getAiSummaryAction(findings);

    if (result.success) {
      setSummary(result.summary);
    } else {
      setError(result.error || 'An unknown error occurred.');
      toast({
        variant: 'destructive',
        title: 'Error',
        description: result.error || 'Failed to generate AI summary.',
      });
    }

    setIsLoading(false);
  };

  return (
    <Dialog open={isOpen} onOpenChange={setIsOpen}>
      <DialogTrigger asChild>
        <Button variant="outline">
          <Bot className="mr-2 h-4 w-4" />
          AI Summary
        </Button>
      </DialogTrigger>
      <DialogContent className="sm:max-w-[625px]">
        <DialogHeader>
          <DialogTitle>AI-Powered Executive Summary</DialogTitle>
          <DialogDescription>
            A concise summary of the key security findings, generated by AI.
          </DialogDescription>
        </DialogHeader>
        <div className="py-4">
          {summary && !isLoading && (
            <div className="prose prose-sm max-w-none rounded-md border bg-secondary p-4">
                <p>{summary}</p>
            </div>
          )}
          {!summary && !isLoading && (
            <div className="flex flex-col items-center justify-center text-center p-8 border-dashed border-2 rounded-md">
              <Bot className="h-12 w-12 text-muted-foreground mb-4" />
              <p className="text-muted-foreground mb-4">Click below to generate an AI summary of the findings.</p>
              <Button onClick={handleGenerateSummary}>Generate Summary</Button>
            </div>
          )}
          {isLoading && (
            <div className="flex items-center justify-center p-8">
              <Loader2 className="h-8 w-8 animate-spin text-primary" />
              <p className="ml-4">Generating summary...</p>
            </div>
          )}
          {error && (
            <Alert variant="destructive" className="mt-4">
                <AlertTitle>Error</AlertTitle>
                <AlertDescription>{error}</AlertDescription>
            </Alert>
          )}
        </div>
      </DialogContent>
    </Dialog>
  );
}
